/// Flutter icons CoreyIcons
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CoreyIcons
///      fonts:
///       - asset: fonts/CoreyIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CoreyIcons {
  CoreyIcons._();

  static const _kFontFam = 'CoreyIcons';

  static const IconData workout = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData schedule = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData body = const IconData(0xf21e, fontFamily: _kFontFam);
}
